clear;
clc;
close all;

T = readtable('/home/saakee/Research/deep-contact-estimator/Data/CSVFiles/robotstate_0_env7.csv');
out_dir = '/home/saakee/Research/deep-contact-estimator/Data/MatFiles';
out_file = fullfile(out_dir, 'robotstate_env7.mat');

% Make contact signals logical (convert numeric or other types to logical)
contacts = logical([T.lfoot_contact, T.rfoot_contact]);
gait_cycle_contacts = [T.lfoot_contact_plan, T.rfoot_contact_plan];

control_time = T.timestamp';
imu_time = T.timestamp';

imu_acc   = [T.acc_x, T.acc_y, T.acc_z];
imu_omega = [T.omega_x, T.omega_y, T.omega_z];


p = [ ...
    T.fk_left_foot_pos_x,  T.fk_left_foot_pos_y,  T.fk_left_foot_pos_z, ...
    T.fk_right_foot_pos_x, T.fk_right_foot_pos_y, T.fk_right_foot_pos_z];

v = [ ...
    T.fk_left_foot_vel_x,  T.fk_left_foot_vel_y,  T.fk_left_foot_vel_z, ...
    T.fk_right_foot_vel_x, T.fk_right_foot_vel_y, T.fk_right_foot_vel_z];

q = [ ...
    T.joint_pos_left_hip_pitch_joint, ...
    T.joint_pos_left_hip_roll_joint, ...
    T.joint_pos_left_hip_yaw_joint, ...
    T.joint_pos_left_knee_joint, ...
    T.joint_pos_left_ankle_pitch_joint, ...
    T.joint_pos_left_ankle_roll_joint, ...
    T.joint_pos_right_hip_pitch_joint, ...
    T.joint_pos_right_hip_roll_joint, ...
    T.joint_pos_right_hip_yaw_joint, ...
    T.joint_pos_right_knee_joint, ...
    T.joint_pos_right_ankle_pitch_joint, ...
    T.joint_pos_right_ankle_roll_joint];

qd = [ ...
    T.joint_vel_left_hip_pitch_joint, ...
    T.joint_vel_left_hip_roll_joint, ...
    T.joint_vel_left_hip_yaw_joint, ...
    T.joint_vel_left_knee_joint, ...
    T.joint_vel_left_ankle_pitch_joint, ...
    T.joint_vel_left_ankle_roll_joint, ...
    T.joint_vel_right_hip_pitch_joint, ...
    T.joint_vel_right_hip_roll_joint, ...
    T.joint_vel_right_hip_yaw_joint, ...
    T.joint_vel_right_knee_joint, ...
    T.joint_vel_right_ankle_pitch_joint, ...
    T.joint_vel_right_ankle_roll_joint];

tau_est = [ ...
    T.joint_torque_left_hip_pitch_joint, ...
    T.joint_torque_left_hip_roll_joint, ...
    T.joint_torque_left_hip_yaw_joint, ...
    T.joint_torque_left_knee_joint, ...
    T.joint_torque_left_ankle_pitch_joint, ...
    T.joint_torque_left_ankle_roll_joint, ...
    T.joint_torque_right_hip_pitch_joint, ...
    T.joint_torque_right_hip_roll_joint, ...
    T.joint_torque_right_hip_yaw_joint, ...
    T.joint_torque_right_knee_joint, ...
    T.joint_torque_right_ankle_pitch_joint, ...
    T.joint_torque_right_ankle_roll_joint];

%Extra 

F = [ ...
    T.rfoot_grf_x, T.rfoot_grf_y, T.rfoot_grf_z, ...
    T.lfoot_grf_x, T.lfoot_grf_y, T.lfoot_grf_z];

F_contacts = [ ...
    T.rfoot_grt_x, T.rfoot_grt_y, T.rfoot_grt_z, ...
    T.lfoot_grt_x, T.lfoot_grt_y, T.lfoot_grt_z];



save(out_file, ...
    'contacts', ...
    'control_time', ...
    'F', ...
    'F_contacts', ...
    'gait_cycle_contacts', ...
    'imu_acc', ...
    'imu_omega', ...
    'imu_time', ...
    'p', ...
    'q', ...
    'qd', ...
    'tau_est', ...
    'v');